export const DANG_NHAP_ACTION = 'DANG_NHAP_ACTION'
export const SET_THONG_TIN_TAI_KHOAN_ACTION = 'THONG_TIN_TAI_KHOAN_ACTION'
export const DANH_SACH_NGUOI_DUNG = 'DANH_SACH_NGUOI_DUNG'
export const THONG_TIN_NGUOI_DUNG = 'THONG_TIN_NGUOI_DUNG'


